# -*- coding: utf-8 -*-
"""Decision tree.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-dHWLuuQmSOqYuXqpHw3XOec1guTmFV_
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import preprocessing,tree
import math

from google.colab import drive
drive.mount('/content/gdrive')

data = pd.read_csv("/content/gdrive/MyDrive/ml_lab/play_tennis.csv")

from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()

col=data.columns.values.tolist()
col

for i in col:
  data[i]=label_encoder.fit_transform(data[i])

data.head()

from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()

X=data.iloc[:,0:len(col)-1]
Y=data.iloc[:,len(col)-1:]

X

Y

clf=clf.fit(X,Y)

tree.plot_tree(clf)