# -*- coding: utf-8 -*-
"""RegressionCoeff&Lineipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hdh-OCaSk2RRAZ2B5Pvp5qUMcrDqH2wi
"""

import matplotlib.pyplot as plt
import numpy as np
x = [5.0,5.1,5.2,5.3,5.4,5.5,5.6,5.7,5.8]
y = [45,47,48,49,50,52,55,57,58]
x_sum = 0
y_sum = 0

for i in range(len(x)):
    x_sum += x[i]
for i in range(len(y)):
    y_sum +=y[i]

print(x_sum)
print(y_sum)

x_mean = x_sum/len(x)
y_mean = y_sum/len(y)
print("Mean of Height are ",x_mean)
print("Mean of Weight are ",y_mean)

print("The Equation for Linear Regression is Y = W1*X + W0")
num = 0
den =0
for i in range(len(x)):
    num+=(x[i]-x_mean)*(y[i]-y_mean)

for i in range(len(x)):
    den+=(x[i]-x_mean)*(x[i]-x_mean)

W1 = num/den
W0 = y_mean - W1*x_mean

print("The Final Equation is Y = ",W1,"X + ",W0)

#taking user's height as input for calculating weight
x1 = float(input("Enter a height of person : "))
y1 = W1*x1+W0
print("Person Weight predicted as : ", y1,"kg")

#Plotting garph for best fit line and points
X = np.linspace(5, 6, 100)
Y = 16.5*X- 37.88
plt.scatter(x,y)
plt.plot(X,Y)
plt.xlabel('height in feet')
plt.ylabel('weight in kg')
plt.title('Height-Weight Dataset')
plt.show()